FROM node:22-alpine AS build

WORKDIR /server

COPY package.json package.json

RUN npm install 

COPY . .

RUN npm run build

FROM node:22-alpine AS runner

WORKDIR /app

COPY --from=build /server/node_modules node_modules/
COPY --from=build /server/package.json package.json
COPY --from=build /server/dist dist/
COPY --from=build /server/.env .env

EXPOSE 8000

CMD ["npm","run","start"]





